In [1]:
#Reversing a 1D Array (Vector):
#For a 1D array, you can use the [::-1] slicing notation to reverse the order of elements. This creates a new reversed array without modifying the original.
#Example:


import numpy as np

array = np.array([1, 2, 3, 4, 5])
reversed_array = array[::-1]

print("Original array:", array)
print("Reversed array:", reversed_array)


Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


In [2]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
reversed_array = np.flip(array)
print("Original array:", array)
print(reversed_array)


Original array: [1 2 3 4 5 6]
[6 5 4 3 2 1]


In [3]:
#Reversing a 2D Array :
#using the np.flip() function to reverse the rows, columns, or both.
#Examples:
#Reversing rows (along the first axis):


array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = np.flip(array, axis=0)

print("Original array:")
print(array)
print("\nReversed rows:")
print(reversed_rows)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reversed rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [4]:
#Reversing Rows (Axis 0)
#using slicing with [::-1, :]:

reversed_rows_arr = array[::-1, :]
print(reversed_rows_arr)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [5]:
#Reversing columns (along the second axis):

reversed_columns= np.flip(array, axis=1)

print("Reversed columns:")
print(reversed_columns)

Reversed columns:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [6]:
#Reversing Columns (Axis 1)
#To reverse the columns of a 2D array, you can use slicing with [:, ::-1]:

reversed_columns_arr = array[:, ::-1]
print(reversed_columns_arr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [7]:
#Reversing both rows and columns:

reversed_both = np.flip(array, axis=(0, 1))

print("Reversed both array:")
print(reversed_both)

Reversed both array:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
